version: '3.9'
services:
  user-mongodb:
    image : mongo:5.0.0
    container_name: user-mongodb
    volumes:
      - mongodb-data:/data/user-db
    ports:
      - 27018:27017
    restart: always
  company-mongodb:
    image : mongo:5.0.0
    container_name: conpany-mongodb
    volumes:
      - mongodb-data:/data/conpany-db
    ports:
      - 27019:27017
    restart: always
  vacancy-mongodb:
    image : mongo:5.0.0
    container_name: vacancy-mongodb
    volumes:
      - mongodb-data:/data/vacancy-db
    ports:
      - 27020:27017
    restart: always

volumes:
  mongodb-data:
    name: mongodb-data